server=/microsoft-smb.cn/114.114.114.114
server=/msauth.cn/114.114.114.114
server=/msftauth.cn/114.114.114.114
server=/sharepoint.cn/114.114.114.114
server=/dl.delivery.mp.microsoft.com/114.114.114.114
server=/download.windowsupdate.com/114.114.114.114
server=/bg.v4.a.dl.ws.microsoft.com/114.114.114.114
server=/bg4.v4.a.dl.ws.microsoft.com/114.114.114.114
server=/cdn.marketplaceimages.windowsphone.com/114.114.114.114
server=/cn.windowssearch.com/114.114.114.114
server=/ctldl.windowsupdate.com/114.114.114.114
server=/developer.microsoft.com/114.114.114.114
server=/docs.microsoft.com/114.114.114.114
server=/download.microsoft.com/114.114.114.114
server=/download.visualstudio.microsoft.com/114.114.114.114
server=/fs.microsoft.com/114.114.114.114
server=/msgr.dlservice.microsoft.com/114.114.114.114
server=/msgruser.dlservice.microsoft.com/114.114.114.114
server=/officecdn.microsoft.com/114.114.114.114
server=/qh.dlservice.microsoft.com/114.114.114.114
server=/sdx.microsoft.com/114.114.114.114
server=/silverlight.dlservice.microsoft.com/114.114.114.114
server=/slupdate.dlservice.microsoft.com/114.114.114.114
server=/storeedgefd.dsx.mp.microsoft.com/114.114.114.114
server=/wl.dlservice.microsoft.com/114.114.114.114
server=/wscont1.apps.microsoft.com/114.114.114.114
server=/wscont2.apps.microsoft.com/114.114.114.114
server=/www.microsoft.com/114.114.114.114
server=/xb.dlservice.microsoft.com/114.114.114.114
