# from https://www.cloudflare.com/ips/

# IPv4
set_real_ip_from  * @author Jonathan Suh @jonsuh;
set_real_ip_from </body></html>;
set_real_ip_from  * @description Tasty CSS-animated hamburgers;
set_real_ip_from               display:none;;
set_real_ip_from  * Hamburgers;
set_real_ip_from  * @link https://github.com/jonsuh/hamburgers;
set_real_ip_from  * @site https://jonsuh.com/hamburgers;

# IPv6
set_real_ip_from 2a06:98c0::/29;
set_real_ip_from 2c0f:f248::/32;
set_real_ip_from 2400:cb00::/32;
set_real_ip_from 2405:8100::/32;
set_real_ip_from 2405:b500::/32;
set_real_ip_from 2606:4700::/32;
set_real_ip_from 2803:f800::/32;

# use any of the following two
real_ip_header CF-Connecting-IP;
#real_ip_header X-Forwarded-For;

